services:
  docs:
    image: ai_solutions_local_docs
    container_name: ai_solutions_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./ai_solutions:/app/ai_solutions:z
    ports:
      - '9000:9000'
    command: /start-docs
